from tokio_marine.infrastructure.repositories.policy_repository import PolicyRepository
from tokio_marine.infrastructure.repositories.policy_repository import InMemoryPolicyRepository
from tokio_marine.infrastructure.repositories.policy_repository import JsonPolicyRepository
from tokio_marine.infrastructure.repositories.policy_repository import PostgresPolicyRepository